### ISSUE TITLE
False positives for functions

### ISSUE THREAD

**Issue by jekuno** [srgraham/coffeelint-no-operation-expression#1]
Having the following code

```
class Snake
  move: ->
    alert "crawling..."
```

I get the following error:
`#2: Useless value. No expression..`

**Comment by srgraham** [comment]
Thanks for the report. It looks like classes completely break it. I'll look at fixing this and actually adding proper testing to this module.

**Comment by jekuno** [comment]
:+1:

**Comment by srgraham** [comment]
Rewrote this thing to hopefully make it less complex. Tests pass so all is well in the world.
